config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  resources :users
  resources :productcategories
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/productcategory.rb
class Productcategory < ApplicationRecord
	#has_many :products
end

app/controllers/productcategories_controller.rb
class ProductcategoriesController < ApplicationController
  before_action :set_productcategory, only: [:show, :edit, :update, :destroy]

  # GET /productcategories
  # GET /productcategories.json
  def index
    @productcategories = Productcategory.all
  end

  # GET /productcategories/1
  # GET /productcategories/1.json
  def show
  end

  # GET /productcategories/new
  def new
    @productcategory = Productcategory.new
  end

  # GET /productcategories/1/edit
  def edit
  end

  # POST /productcategories
  # POST /productcategories.json
  def create
    @productcategory = Productcategory.new(productcategory_params)

    respond_to do |format|
      if @productcategory.save
        format.html { redirect_to @productcategory, notice: 'Productcategory was successfully created.' }
        #format.json { render :show, status: :created, location: @productcategory }
      else
        format.html { render :new }
        #format.json { render json: @productcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productcategories/1
  # PATCH/PUT /productcategories/1.json
  def update
    respond_to do |format|
      if @productcategory.update(productcategory_params)
        format.html { redirect_to @productcategory, notice: 'Productcategory was successfully updated.' }
        #format.json { render :show, status: :ok, location: @productcategory }
      else
        format.html { render :edit }
        #format.json { render json: @productcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productcategories/1
  # DELETE /productcategories/1.json
  def destroy
    @productcategory.destroy
    respond_to do |format|
      format.html { redirect_to productcategories_url, notice: 'Productcategory was successfully destroyed.' }
      #format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_productcategory
      @productcategory = Productcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def productcategory_params
      params.require(:productcategory).permit(:CategoryID, :CategoryName)
    end
end

app/helpers/productcategories_helper.rb
module ProductcategoriesHelper
end

app/views/productcategories/_form.html.haml
= form_with(model: productcategory, local: true) do |form|
  - if productcategory.errors.any?
    #error_explanation
      %h2
        = pluralize(productcategory.errors.count, "error")
        prohibited this productcategory from being saved:
      %ul
        - productcategory.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :CategoryID
    = form.text_field :CategoryID, id: :productcategory_CategoryID
  .field
    = form.label :CategoryName
    = form.text_field :CategoryName, id: :productcategory_CategoryName
  .actions
    = form.submit

app/views/productcategories/edit.html.haml
%h1 Editing Productcategory
= render 'form', productcategory: @productcategory
= link_to 'Show', @productcategory
|
= link_to 'Back', productcategories_path

app/views/productcategories/index.html.haml
%p#notice= notice
%h1{:align => "center", :style => "color:blue"} PRODUCT CATEGORIES SETTING
%table{:align => "center", :border => "1px"}
  %thead
    %tr
      %th{:style => "color:green"} ID
      %th{:style => "color:green"} Category Name
      %th{:colspan => "3"}
  %tbody
    - @productcategories.each do |productcategory|
      %tr
        %td= productcategory.CategoryID
        %td= productcategory.CategoryName
        %td= link_to 'Show', productcategory
        %td= link_to 'Edit', edit_productcategory_path(productcategory)
        %td= link_to 'Destroy', productcategory, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Productcategory', new_productcategory_path

app/views/productcategories/new.html.haml
%h1 New Productcategory
= render 'form', productcategory: @productcategory
= link_to 'Back', productcategories_path

app/views/productcategories/show.html.haml
%p#notice= notice
%p
  %strong Categoryid:
  = @productcategory.CategoryID
%p
  %strong Categoryname:
  = @productcategory.CategoryName
= link_to 'Edit', edit_productcategory_path(@productcategory)
|
= link_to 'Back', productcategories_path